### ISSUE TITLE
Swallowed IllegalArgumentException from MultiSampleGaugeMeasurement

### ISSUE THREAD

**Issue by neilellis** [librato/metrics-librato#29]
I could not send any data to Librato using 3.0.0-BETA2.0-RC1, so with some debugging:

In LibratorReporter.report:

```
 batch.addSampling(entry.getKey(),entry.getValue)
```

The Histogram can have a size of zero which triggers in 
MultiSampleGaugeMeasurement:

```
  if (count == null || count == 0) {
        throw new IllegalArgumentException("The Librato API requires the count to be > 0 for complex metrics. See http://dev.librato.com/v1/post/metrics");
    }
```

For my own purposes I added a zero check (in LibratoReporter) and now can send data to librato:

```
 if(sampling.getSnapshot().size() != 0) {
            batch.addSampling(entry.getKey(), sampling);
 }
```

Also you definitely need to catch all errors in LibratoReporter.report(...) as they get swallowed by the executor.

Hope that helps,
Neil

**Comment by mheffner** [comment]
Thanks for your submission. AppOptics is the next generation of Librato and is built on the same backend, but with additional support for APM and distributed tracing. We are moving future development of this client to https://github.com/appoptics/metrics-appoptics.
