### ISSUE TITLE
MultiSampleGaugeMeasurement should be configurable via the expansion config

### ISSUE THREAD

**Issue by carllerche** [librato/metrics-librato#46]
I'm personally not really interested in the MultiSampleGaugeMeasurement. It would be nice to be able to opt out.

**Comment by mheffner** [comment]
Thanks for your submission. AppOptics is the next generation of Librato and is built on the same backend, but with additional support for APM and distributed tracing. We are moving future development of this client to https://github.com/appoptics/metrics-appoptics.
