### ISSUE TITLE
Upgrade to latest Codahale Metrics

### ISSUE THREAD

**Issue by baank** [librato/metrics-librato#60]
Many frameworks e.g. Dropwizard are now using a later version of Codahale Metrics e.g. 3.1.1

It would be good to update to prevent classpath issues.

**Comment by ahepburn** [comment]
I created this [PR-61] (https://github.com/librato/metrics-librato/pull/61) to address this, we'd prefer not to have both on our classpath...

**Comment by mheffner** [comment]
Thanks for your submission. AppOptics is the next generation of Librato and is built on the same backend, but with additional support for APM and distributed tracing. We are moving future development of this client to https://github.com/appoptics/metrics-appoptics.
