### ISSUE TITLE
Add support to configure and apply Service Side Aggregation

### ISSUE THREAD

**Issue by gmckeever** [librato/metrics-librato#76]
It would be useful to offer an option to enable aggregation and set a period for metrics reported to Librato. Documentation for setting the `period` and `aggregation` can be found here:

https://www.librato.com/docs/api/#measurement-properties

**Comment by mheffner** [comment]
Thanks for your submission. AppOptics is the next generation of Librato and is built on the same backend, but with additional support for APM and distributed tracing. We are moving future development of this client to https://github.com/appoptics/metrics-appoptics.
