### ISSUE TITLE
What are the units for SpringBoot metrics LibratoReporter sends to Librato?

### ISSUE THREAD

**Issue by diego-carvallo-tx** [librato/metrics-librato#82]
I am using the Librato Reporte to send autoconfigured SpringBoot metrics to Librato. The generated metrics are:
ComplexGauge: name=foo
Gauge: name=foo.median
Gauge: name=foo.75th
Gauge: name=foo.95th
Gauge: name=foo.98th
Gauge: name=foo.99th
Gauge: name=foo.999th
DeltaGauge: name=foo.count 
Gauge: name=foo.meanRate
Gauge: name=foo.1MinuteRate
Gauge: name=foo.5MinuteRate
Gauge: name=foo.15MinuteRate

But I cannot find anywhere what the units are for each metric. Do you guys mind replying with the units for each one? thanks a lot.

**Comment by mheffner** [comment]
Hi @diego-carvallo-tx ,

Are you referring to the [Timer](https://github.com/librato/metrics-librato#coda-timers) type? By default they are reported as Milliseconds, you can change [the default](https://github.com/librato/metrics-librato/blob/7a2df776d627b2852679b5617ae4d8b3bff7927c/src/main/java/com/librato/metrics/reporter/ReporterAttributes.java#L19) if you need to.

The `foo.count` metric includes a number of times the Timer code has been updated, usually corresponding to the request rate. The `*Rate` metrics all correspond to pre-calculated request-rate metrics at different intervals. The remaining metrics are all given percentiles of the timer samples, as measured in Milliseconds.

**Comment by diego-carvallo-tx** [comment]
Could you help me complete/correct this table so I can correctly interpret the charts I see in Librato when using the LibratoReporter?

Metric | Units | Interpretation
-- | -- | --
foo | ??? | ???
foo.count | requests | overal number of   requests since server start???
foo.median | requests/minute??? | median fo requests   per minute???
foo.1MinuteRate | requests/minute | moving average   number of requests per second within the last minute
foo.5MinuteRate | requests/5minutes | moving average   number of requests per second within the last 5 minutes
foo.15MinuteRate | requests/15minutes | moving average   number of requests per second within the last 15 minutes
foo.meanRate | requests/minute??? | average number or   requests per minute??? per second???
foo.75th | ??? | 75th percentile:   75% of the time the requests are below what units???
foo.95th |   | "
foo.98th |   | "
foo.99th |   | "
foo.999th |   | "


Based on info found at https://reflectoring.io/transparency-with-spring-boot/

**Comment by mheffner** [comment]
@diego-carvallo-tx sure, let me give it a shot:

Metric | Units | Interpretation
-- | -- | --
foo | milliseconds | avg, sum, min and max of all times in milliseconds (see [Summary Fields](https://docs.appoptics.com/api/#create-a-measurement))
foo.{75th, 95th, 99th, ...} | milliseconds  | Nth percentile of time the requests are below given milliseconds
-- | -- | --

If you are using Spring Boot, you may also be interested in our recent addition of AppOptics support to micrometer.io: https://github.com/micrometer-metrics/micrometer/pull/705. [AppOptics](www.appoptics.com) is the new replacement for Librato that includes APM and distributed tracing. It is built on the Librato framework and supports all the common Librato features.

**Comment by diego-carvallo-tx** [comment]
Thanks, still didn't find what I need. Let me put it in a different way:

If I need a chart of the average time (in seconds) spent per request, which one should I use?

Thanks a lot for your help.

**Comment by mheffner** [comment]
> If I need a chart of the average time (in seconds) spent per request, which one should I use?

If you want average time "in seconds", you'll need to plot just the metric `foo` and add a [display transform](https://docs.appoptics.com/kb/faq/display_transform/) of `x/1000` to convert milliseconds -> seconds.

**Comment by mheffner** [comment]
Thanks for your submission. AppOptics is the next generation of Librato and is built on the same backend, but with additional support for APM and distributed tracing. We are moving future development of this client to https://github.com/appoptics/metrics-appoptics.
